//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPS.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DestinationNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DestinationNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPS.Management.DestinationNames", typeof(DestinationNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/AddTask.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/DeleteTask.
        /// </summary>
        internal static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/DownloadAttachments?Id=.
        /// </summary>
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/ManagementGetEmployeeFeedbacks.
        /// </summary>
        internal static string GetEmployeeFeedbacks {
            get {
                return ResourceManager.GetString("GetEmployeeFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/ManagementGetEmployees.
        /// </summary>
        internal static string GetEmployees {
            get {
                return ResourceManager.GetString("GetEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/ManagementGetFeedbacks.
        /// </summary>
        internal static string GetFeedbacks {
            get {
                return ResourceManager.GetString("GetFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/GetProjects.
        /// </summary>
        internal static string GetProjects {
            get {
                return ResourceManager.GetString("GetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/GetSeverities.
        /// </summary>
        internal static string GetSeverities {
            get {
                return ResourceManager.GetString("GetSeverities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/GetStates.
        /// </summary>
        internal static string GetStates {
            get {
                return ResourceManager.GetString("GetStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/GetEmployees.
        /// </summary>
        internal static string GetTaskEmployees {
            get {
                return ResourceManager.GetString("GetTaskEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/GetTasks.
        /// </summary>
        internal static string GetTasks {
            get {
                return ResourceManager.GetString("GetTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/ManagementLeaveFeedback.
        /// </summary>
        internal static string LeaveFeedback {
            get {
                return ResourceManager.GetString("LeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/ManagementUpdateEmployee.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/DAL/UploadAttachments.
        /// </summary>
        internal static string UploadAttachment {
            get {
                return ResourceManager.GetString("UploadAttachment", resourceCulture);
            }
        }
    }
}
