//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPS.ServiceLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DestinationNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DestinationNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPS.ServiceLayer.DestinationNames", typeof(DestinationNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/Notification/AddEvent.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/HR/HRPost.
        /// </summary>
        internal static string AddHREmployee {
            get {
                return ResourceManager.GetString("AddHREmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/AddTask.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Finance/DeleteEmployee.
        /// </summary>
        internal static string DeleteEmployeeFinance {
            get {
                return ResourceManager.GetString("DeleteEmployeeFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/HR/HRDeleteEmployee.
        /// </summary>
        internal static string DeleteHREmployee {
            get {
                return ResourceManager.GetString("DeleteHREmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/DeleteTask.
        /// </summary>
        internal static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/DownloadAttachments?Id=.
        /// </summary>
        internal static string DownloadAttachment {
            get {
                return ResourceManager.GetString("DownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/HR/GetCandidateList.
        /// </summary>
        internal static string GEtCandidates {
            get {
                return ResourceManager.GetString("GEtCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Finance/GetEmployeeById.
        /// </summary>
        internal static string GetEmployeeFinanceById {
            get {
                return ResourceManager.GetString("GetEmployeeFinanceById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Finance/GetAllEmployees.
        /// </summary>
        internal static string GetFinanceEmployees {
            get {
                return ResourceManager.GetString("GetFinanceEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/HR/GetEmployeeHRById.
        /// </summary>
        internal static string GetHREmployeeId {
            get {
                return ResourceManager.GetString("GetHREmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/HR/GetEmployeesHR.
        /// </summary>
        internal static string GetHREmployees {
            get {
                return ResourceManager.GetString("GetHREmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /API/Notification/GetNotifications.
        /// </summary>
        internal static string GetNotifications {
            get {
                return ResourceManager.GetString("GetNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/GetProjects.
        /// </summary>
        internal static string GetProjects {
            get {
                return ResourceManager.GetString("GetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/GetSeverities.
        /// </summary>
        internal static string GetSeverities {
            get {
                return ResourceManager.GetString("GetSeverities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/GetStates.
        /// </summary>
        internal static string GetStates {
            get {
                return ResourceManager.GetString("GetStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/GetEmployees.
        /// </summary>
        internal static string GetTaskEmployees {
            get {
                return ResourceManager.GetString("GetTaskEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/GetTasks.
        /// </summary>
        internal static string GetTasks {
            get {
                return ResourceManager.GetString("GetTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Management/GetEmployeeFeedbacks.
        /// </summary>
        internal static string ManagementGetEmployeeFeedbacks {
            get {
                return ResourceManager.GetString("ManagementGetEmployeeFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Management/GetEmployees.
        /// </summary>
        internal static string ManagementGetEmployees {
            get {
                return ResourceManager.GetString("ManagementGetEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Management/GetFeedbacks.
        /// </summary>
        internal static string ManagementGetFeedbacks {
            get {
                return ResourceManager.GetString("ManagementGetFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Management/LeaveFeedback.
        /// </summary>
        internal static string ManagementLeaveFeedback {
            get {
                return ResourceManager.GetString("ManagementLeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Management/UpdateEmployee.
        /// </summary>
        internal static string ManagementUpdateEmployee {
            get {
                return ResourceManager.GetString("ManagementUpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Finance/UpdateEmployee.
        /// </summary>
        internal static string UpdateEmployeeFinance {
            get {
                return ResourceManager.GetString("UpdateEmployeeFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/Task/UploadAttachments.
        /// </summary>
        internal static string UploadAttachment {
            get {
                return ResourceManager.GetString("UploadAttachment", resourceCulture);
            }
        }
    }
}
